config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :bookings
  resources :customers

  root to: "bookings#new"

  devise_scope :admin do
    get 'sign_in', to: 'devise/sessions#new'
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
    before_create :pricing_engine
    before_update :pricing_engine

    enum status: { confirmed: 0, cancled: 1, in_progress: 2, completed: 3 }
    enum animal_type: { dog: 0, cat: 1 }

    def full_name
        self.first_name + " " + self.last_name
    end

    def pricing_engine
        hourly_pricing = { "dog" => 10, "cat" => 5 }
        self.price = 20 + ( self.hours * hourly_pricing[self.animal_type])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_admin!, only: %i[ index ]
  before_action :set_booking, only: %i[ show edit update destroy ]

  # GET /bookings or /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1 or /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings or /bookings.json
  def create
    @booking = Booking.new(booking_params)

    respond_to do |format|
      if @booking.save
        format.html { redirect_to booking_url(@booking), notice: "Booking was successfully created." }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1 or /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to booking_url(@booking), notice: "Booking was successfully updated." }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1 or /bookings/1.json
  def destroy
    @booking.destroy

    respond_to do |format|
      format.html { redirect_to bookings_url, notice: "Booking was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def booking_params
      params.require(:booking).permit(:first_name, :last_name, :animal_name, :animal_type, :address, :service_date, :hours)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/bookings/_booking.html.erb
<div id="<%= dom_id booking %>">

    <div>Hi <%= booking.full_name %>, </div>

    <div>We are excited to watch your <%=  booking.animal_type %> <span class="text-green font-bold"><%= booking.animal_name %></span> on</div>
    <div><%= booking.service_date.strftime('%m/%d/%Y') %> for <%= booking.hours %> hours.</div>

    <div class="mt-6 text-green">Price: $<%= booking.price %></div>

</div>

app/views/bookings/_form.html.erb
<%= form_with(model: booking) do |form| %>
  <% if booking.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
        <% booking.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex flex-col w-fill">
    <div class="flex">
      <div class="flex flex-col mr-10">
        Customer Information

        <%= form.text_field :first_name, placeholder: "First Name", class: "my-2 border-light_grey" %>

        <%= form.text_field :last_name, placeholder: "Last Name", class: "my-2 border-light_grey" %>

        <%= form.text_field :animal_name, placeholder: "Animal Name", class: "my-2 border-light_grey" %>

        <%= form.text_field :address, placeholder: "Your Address", class: "my-2 border-light_grey" %>

        <%= form.select :animal_type, options_for_select(Booking.animal_types.map { |key, value| [key.humanize, key] }, @booking.animal_type), class: "my-2 border-light_grey" %>
      </div>

      <div class="flex flex-col">
        Sit Schedule

        <%= form.date_field :service_date, class: "my-2 border-light_grey" %>

        <%= form.number_field :hours, in: 2..8, step: 1, value: @booking.hours == 0 ? 2 : @booking.hours, class: "my-2 border-light_grey" %>
      </div>
    </div>
    <button class="bg-green px-6 py-2 text-white font-bold mt-6 w-fill">
      <%= form.submit "#{ @booking ? "Update" : "Book"} Your PetSit" %>
    </button>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<div class="text-3xl">Editing booking</div>

<%= render "form", booking: @booking %>

<br>

<div>
  <%= link_to "Go Back", @booking %>
</div>

app/views/bookings/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="text-3xl">Bookings</div>

<div class="mt-10" id="bookings">


  <table class="table-auto">
    <thead>
      <tr class="p-6">
        <th class="text-left px-12 py-4">Status</th>
        <th class="text-left px-12 py-4">Date</th>
        <th class="text-left px-12 py-4">Hours</th>
        <th class="text-left px-12 py-4">Price</th>
        <th class="text-left px-12 py-4">Name</th>
        <th class="text-left px-12 py-4">Pet</th>
        <th class="text-left px-12 py-4">type</th>
      </tr>
    </thead>
    <tbody class="bg-white p-6 text-center">
      <% @bookings.each do |booking| %>

        <tr>
          <td class="p-6"><%= booking.status %></td>
        
          <td class="p-6"><%= booking.service_date.strftime('%m/%d/%Y') %></td>
    
          <td class="p-6"><%= booking.hours %></td>
 
          <td class="p-6">$<%= booking.price %></td>
    
          <td class="p-6"><%= booking.full_name %></td>
      
          <td class="p-6"><%= booking.animal_name %></td>

          <td class="p-6"><%= booking.animal_type %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/bookings/new.html.erb
<div class="flex justify-between w-fill text-grey">
  <div class="mr-14">Secure Checkout</div>
  <div class="mr-14">Guaranteed Price</div>
  <div>Trusted Reviews</div>
</div>

<div class="text-4xl font-extrabold my-16 text-grey">Book Online Now</div>

<%= render "form", booking: @booking %>

<br>

app/views/bookings/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="text-3xl">Your Booking Is Set</div>

<div class="bg-white p-10 my-10 rounded-md">
  <%= render @booking %>
</div>

<div class="">
  <%= link_to "Need to Make A Change?", edit_booking_path(@booking) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetSitUp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-background">
    <div class="flex items-center justify-between border-b-[.5px] border-light_grey bg-white  w-fill h-20 px-6">
      <%= link_to new_booking_path() do %>
        <div class="font-bold text-2xl text-grey">PetSit <span class="text-green">Up!</span></div>
      <% end %>

      <% if admin_signed_in? %> 
        <div class="flex">
          <%= link_to bookings_path() do %><div class="mr-10">Bookings</div><% end%>
          <%= link_to destroy_admin_session_path() do %> Logout <% end %>
        </div>
      <% else %>
        <%= link_to new_admin_session_path() do %> Admin Login <% end %>
      <% end%>
    </div>
    
    <div class="flex flex-col justify-start items-center pt-6">
      <%= yield %>
    </div>
  </body>
</html>